test_set:
  preprocessing: "icp"                         #choices=['icp', 'spatial_transformer', 'none']
  break_ds_with: "rotation_translation"        #choices=['rotation', 'translation', 'rotation_translation', 'none']
  split: "Test"
  ds_path: "./Facescape"
  category: "Neutral"
  references_pointclouds_icp_path: "./Preprocessing/reference_pointclouds_for_icp"
  reduce_pointcloud_to: 1024

# Define the same configuration used during the training
model:
  #name: "SE3Unet"
  n_layers: 2
  si_m: "1x1"
  si_e: "att"
  in_features: 3
  hidden_channels: 5  # ref paper 5
  out_features: 68
  pooling_ratio: 0.25
  aggr: "sum"

checkpoint_fpath: "./checkpoints/run-1.0/checkpoint-1-v0.1.0.0.pth"

hyper:
  batch_size: 2
  device: "cuda"
  features: "v"