test_set:
  preprocessing: "none"                         #choices=['icp', 'spatial_transformer', 'none']
  break_ds_with: "none"        #choices=['rotation', 'translation', 'rotation_translation', 'none']
  split: "Test"
  ds_path: "./Facescape"
  category: "Neutral"
  references_pointclouds_icp_path: "./Preprocessing/reference_pointclouds_for_icp"
  reduce_pointcloud_to: 2048

# Define the same configuration used during the training
model:
  #name: "SE3Unet"
  n_layers: 4
  si_m: "att"
  si_e: "1x1"
  in_features: 3
  hidden_channels: 5  # ref paper 5
  out_features: 68
  pooling_ratio: 0.1
  aggr: "max"

checkpoint_fpath: "./checkpoints/checkpoint-5-v0.0.2.0.pth"

hyper:
  batch_size: 1
  device: "cpu"
  features: "v"